
[worldgen]

	# 
	#Modify Create's impact on your terrain
	[worldgen.v2]
		# 
		#Prevents all worldgen added by Create from taking effect
		disableWorldGen = false

		[worldgen.v2.striated_ores_overworld]
			# 
			#Range: > 0
			minHeight = 9
			# 
			#Range: > 0
			maxHeight = 23
			# 
			#Range: > 0
			clusterSize = 32
			# 
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0555555559694767

		[worldgen.v2.zinc_ore]
			# 
			#Range: > 0
			minHeight = 24
			# 
			#Range: > 0
			maxHeight = 33
			# 
			#Range: > 0
			clusterSize = 8
			# 
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 3.0

		[worldgen.v2.striated_ores_nether]
			# 
			#Range: > 0
			minHeight = 40
			# 
			#Range: > 0
			maxHeight = 75
			# 
			#Range: > 0
			clusterSize = 32
			# 
			#Amount of clusters generated per Chunk.
			#  >1 to spawn multiple.
			#  <1 to make it a chance.
			#  0 to disable.
			#Range: 0.0 ~ 512.0
			frequency = 0.0833333358168602

